[package]
name = "relay_rpc"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[features]
default = ["cacao"]
cacao = [
    "dep:erc6492",
    "dep:alloy-transport",
    "dep:alloy-provider",
    "dep:alloy-primitives",
]

[dependencies]
bs58 = "0.4"
data-encoding = "2.3"
derive_more = { version = "0.99", default-features = false, features = [
    "display",
    "from",
    "as_ref",
    "as_mut",
] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde-aux = { version = "4.1", default-features = false }
serde_json = "1.0"
thiserror = "1.0"
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
rand = "0.8"
chrono = { version = "0.4", default-features = false, features = [
    "std",
    "clock",
] }
regex = "1.7"
once_cell = "1.16"
jsonwebtoken = "8.1"
sha2 = { version = "0.10.6" }
url = "2"
alloy-transport = { git = "https://github.com/alloy-rs/alloy.git", rev = "d68a6b7", optional = true }
alloy-provider = { git = "https://github.com/alloy-rs/alloy.git", rev = "d68a6b7", optional = true }
alloy-primitives = { version = "0.7.0", optional = true }
erc6492 = { git = "https://github.com/WalletConnect/erc6492.git", optional = true }
strum = { version = "0.26", features = ["strum_macros", "derive"] }

[dev-dependencies]
k256 = "0.13"
tokio = { version = "1.35.1", features = ["test-util", "macros"] }
alloy-transport-http = { git = "https://github.com/alloy-rs/alloy.git", rev = "d68a6b7" }
reqwest = "0.12.4"

[lints.clippy]
indexing_slicing = "deny"
