name: ci

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "README.md"

concurrency:
  # Support push/pr as event types with different behaviors each:
  # 1. push: queue up builds
  # 2. pr: only allow one run per PR
  group: ${{ github.workflow }}-${{ github.event_name }}${{ github.event.pull_request.number }}
  # If there is already a workflow running for the same pull request, cancel it
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  tasks:
    name: "${{ matrix.cargo.name }}"
    runs-on:
      group: ubuntu-runners
    strategy:
      fail-fast: false
      matrix:
        cargo:
          - name: "Clippy"
            cmd: clippy
            args: --workspace --all-features --tests -- -D warnings
            rust: stable
          - name: "Formatting"
            cmd: fmt
            args: --all -- --check
            rust: nightly
          - name: "Tests"
            cmd: nextest
            args: run --workspace --all-features --features cacao --retries 3
            rust: stable
          - name: "Documentation Tests"
            cmd: test
            args: --workspace --doc --all-features
            rust: stable
    env:
      RUST_BACKTRACE: full
    steps:
      - uses: actions/checkout@v3

      # Install Rust toolchain
      - name: "Install Rust ${{ matrix.cargo.rust }}"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.cargo.rust }}
          profile: default
          override: true

      # Install nightly which is required for supporting `-Z minimal-versions`
      # https://github.com/rust-lang/cargo/issues/5657
      - name: "Install Rust nightly"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal

      - uses: Swatinem/rust-cache@v2

      - uses: taiki-e/install-action@v1
        with:
          tool: nextest

      # Install the minimal versions this package says it supports
      # https://users.rust-lang.org/t/psa-please-specify-precise-dependency-versions-in-cargo-toml/71277
      # https://github.com/rust-lang/cargo/issues/5657
      - name: "Install minimal package versions"
        run: cargo +nightly -Z minimal-versions update

      - name: "Cargo ${{ matrix.cargo.name }}"
        uses: actions-rs/cargo@v1
        with:
          command: ${{ matrix.cargo.cmd }}
          args: ${{ matrix.cargo.args }}

  misspell:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
